// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Backend.Domain.Entites;
using Microsoft.EntityFrameworkCore;

namespace Backend.Infrastructure.Models;

public partial class BackendDBContext : DbContext
{
    public BackendDBContext()
    {
    }

    public BackendDBContext(DbContextOptions<BackendDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Product> Products { get; set; }
    public virtual DbSet<ProductDetail> ProductDetails { get; set; }

    //=> optionsBuilder.UseSqlServer("Data Source=LAPTOP-L5M2A9CJ\\MSSQLSERVER19;Initial Catalog=BackendDB;Persist Security Info=True;User ID=sa;Password=sa123");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.ProductID).HasName("PK__Product__B40CC6ED2BEF9605");
        });

        modelBuilder.Entity<ProductDetail>(entity =>
        {
            entity.HasKey(e => e.DetailID).HasName("PK__ProductD__135C314DA6C834E0");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductDetails).HasConstraintName("FK_ProductDetails_ProductID");
        });

        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingGeneratedFunctions(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}