// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Backend.Infrastructure.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Backend.Infrastructure.Models
{
    public partial class BackendDBContext
    {
        private IBackendDBContextProcedures _procedures;

        public virtual IBackendDBContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new BackendDBContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IBackendDBContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
        }
    }

    public partial class BackendDBContextProcedures : IBackendDBContextProcedures
    {
        private readonly BackendDBContext _context;

        public BackendDBContextProcedures(BackendDBContext context)
        {
            _context = context;
        }
    }
}
