// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Backend.Infrastructure.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Backend.Infrastructure.Models
{
    public partial interface IBackendDBContextProcedures
    {
    }
}
